-- AI Milestone Rules seed data
-- Standard Australian preventative maintenance rules
-- Run once against the production database

INSERT INTO ai_milestone_rules
  (title, description, trigger_odometer, trigger_odometer_repeat, trigger_age_months, trigger_age_repeat_months,
   applies_to_fuel_type, applies_to_vehicle_age_min_years, applies_to_vehicle_age_max_years, applies_to_make,
   recommended_service_type, recommendation_title, recommendation_body, urgency,
   estimated_cost_min, estimated_cost_max, suppress_if_done, suppress_if_done_within_months, is_active, sort_order)
VALUES

-- ── Recurring odometer-based ──────────────────────────────────────────────────

('Oil & filter change',
 'Regular engine oil and filter replacement.',
 10000, 10000, 6, 6,
 'petrol,diesel,hybrid,lpg', NULL, NULL, NULL,
 'Oil & Filter Change',
 'Your {{vehicleLabel}} is due for an oil & filter change',
 'Fresh oil is the single most important thing you can do to extend engine life. Dirty oil accelerates wear on internal components and can void your warranty. We recommend an oil and filter change every 10,000 km or 6 months — whichever comes first.',
 'recommended',
 89.00, 149.00, 1, 4, 1, 10),

('Tyre rotation',
 'Rotate tyres to even out tread wear across all four corners.',
 10000, 10000, NULL, NULL,
 'all', NULL, NULL, NULL,
 'Tyre Rotation',
 'Time to rotate the tyres on your {{vehicleLabel}}',
 'Rotating your tyres every 10,000 km evens out tread wear, extends tyre life by up to 30%, and keeps handling predictable. It takes about 20 minutes and can save you hundreds on early tyre replacement.',
 'advisory',
 40.00, 70.00, 1, 3, 1, 20),

('Air filter replacement',
 'Engine air filter replacement for petrol, diesel and hybrid vehicles.',
 30000, 30000, 24, 24,
 'petrol,diesel,hybrid,lpg', NULL, NULL, NULL,
 'Air Filter Replacement',
 'Engine air filter due on your {{vehicleLabel}}',
 'A clogged air filter reduces engine performance and fuel economy by up to 10%. Australian dust conditions mean air filters can block faster than manufacturer estimates. We recommend replacement every 30,000 km or 2 years.',
 'recommended',
 45.00, 95.00, 1, 12, 1, 30),

('Cabin air filter replacement',
 'Pollen and dust filter for the cabin air system.',
 20000, 20000, 12, 12,
 'all', NULL, NULL, NULL,
 'Cabin Air Filter',
 'Cabin air filter due on your {{vehicleLabel}}',
 'The cabin air filter cleans the air entering your car through the heating and air conditioning system. A dirty filter reduces airflow, causes musty smells, and lets dust and pollen into the cabin. Replace every 20,000 km or 12 months.',
 'advisory',
 40.00, 90.00, 1, 6, 1, 40),

('Brake fluid flush',
 'Replace hygroscopic brake fluid to maintain braking performance.',
 40000, 40000, 24, 24,
 'all', NULL, NULL, NULL,
 'Brake Fluid Flush',
 'Brake fluid flush due on your {{vehicleLabel}}',
 'Brake fluid absorbs moisture from the air over time, which lowers its boiling point and can cause brake fade under hard use. A flush every 40,000 km or 2 years keeps your braking system safe and reliable.',
 'important',
 89.00, 149.00, 1, 12, 1, 50),

('Coolant flush',
 'Replace engine coolant to prevent corrosion and overheating.',
 60000, 60000, 36, 36,
 'petrol,diesel,hybrid,lpg', NULL, NULL, NULL,
 'Coolant Flush',
 'Coolant flush due on your {{vehicleLabel}}',
 'Old coolant loses its corrosion inhibitors and anti-freeze properties. A flush every 60,000 km or 3 years prevents corrosion inside the radiator, heater core, and water pump — components that are expensive to replace.',
 'recommended',
 149.00, 249.00, 1, 18, 1, 60),

('Automatic transmission service',
 'Replace automatic transmission fluid to prevent slipping and wear.',
 60000, 60000, NULL, NULL,
 'petrol,diesel,hybrid,lpg', NULL, NULL, NULL,
 'Automatic Transmission Service',
 'Transmission service due on your {{vehicleLabel}}',
 'Automatic transmission fluid degrades with heat and use, causing wear to internal components and eventually slipping or failure. Replacing the fluid every 60,000 km is far cheaper than a transmission rebuild.',
 'recommended',
 199.00, 349.00, 1, 24, 1, 70),

('Spark plugs replacement',
 'Standard copper or platinum spark plug replacement for petrol engines.',
 40000, 40000, NULL, NULL,
 'petrol,lpg', NULL, NULL, NULL,
 'Spark Plugs',
 'Spark plugs due on your {{vehicleLabel}}',
 'Worn spark plugs cause hard starting, rough idle, poor fuel economy, and misfires. Standard spark plugs should be replaced every 40,000 km to keep your engine running cleanly and efficiently.',
 'recommended',
 149.00, 299.00, 1, 12, 1, 80),

('Drive belt inspection & replacement',
 'Serpentine and accessory drive belt check and replacement.',
 60000, 40000, 48, 36,
 'petrol,diesel,hybrid,lpg', NULL, NULL, NULL,
 'Drive Belt Service',
 'Drive belt service due on your {{vehicleLabel}}',
 'The drive belt powers your alternator, power steering pump, and air conditioning compressor. A snapped belt leaves you stranded and can damage other components. Inspect from 60,000 km and replace every 100,000 km or sooner if cracked or glazed.',
 'recommended',
 149.00, 299.00, 1, 18, 1, 90),

('Timing belt inspection',
 'Advisory check — confirm if vehicle has a timing belt or chain.',
 80000, NULL, NULL, NULL,
 'petrol,diesel,lpg', NULL, NULL, NULL,
 'Timing Belt Check',
 'Timing belt check recommended for your {{vehicleLabel}}',
 'At 80,000 km it\'s worth confirming whether your engine has a timing belt or chain. Timing belts are typically replaced at 100,000 km — failure can cause serious internal engine damage. Timing chains generally last the life of the engine with good oil maintenance.',
 'advisory',
 NULL, NULL, 0, NULL, 1, 100),

('Timing belt replacement',
 'Timing belt, tensioner and water pump replacement at 100,000 km.',
 100000, 100000, NULL, NULL,
 'petrol,diesel,lpg', NULL, NULL, NULL,
 'Timing Belt Replacement',
 'Timing belt replacement due on your {{vehicleLabel}}',
 'If your engine has a rubber timing belt, replacement at 100,000 km is critical. A broken timing belt causes catastrophic engine failure — bent valves, damaged pistons, and a repair bill that can exceed the value of the car. Book this before your next long trip.',
 'urgent',
 549.00, 899.00, 1, 36, 1, 110),

('Fuel filter replacement',
 'In-line fuel filter replacement for petrol and diesel vehicles.',
 40000, 40000, 24, 24,
 'petrol,diesel,lpg', NULL, NULL, NULL,
 'Fuel Filter',
 'Fuel filter due on your {{vehicleLabel}}',
 'A blocked fuel filter starves the engine of fuel, causing poor performance and hard starting, and puts extra load on your fuel pump. Replacement every 40,000 km or 2 years keeps fuel delivery clean and your pump running longer.',
 'recommended',
 79.00, 149.00, 1, 12, 1, 120),

('Power steering fluid check',
 'Inspect and top up or replace power steering fluid.',
 40000, 40000, 24, 24,
 'petrol,diesel,hybrid,lpg', NULL, NULL, NULL,
 'Power Steering Fluid',
 'Power steering fluid check due on your {{vehicleLabel}}',
 'Old power steering fluid breaks down and can cause noise, stiff steering, and eventual pump failure. A fluid check and replacement every 40,000 km or 2 years keeps your steering smooth and protects the pump.',
 'advisory',
 59.00, 119.00, 1, 12, 1, 130),

('Brake pad inspection',
 'Measure brake pad thickness and inspect rotors.',
 30000, 20000, 18, 18,
 'all', NULL, NULL, NULL,
 'Brake Inspection',
 'Brake pad inspection due on your {{vehicleLabel}}',
 'Brake pads wear at different rates depending on driving style and conditions. A quick inspection every 30,000 km or 18 months catches worn pads before they damage rotors — rotor replacement costs 3x more than a pad swap. If you hear squealing, don\'t wait.',
 'recommended',
 79.00, 149.00, 1, 9, 1, 140),

('Differential fluid',
 'Replace front and rear differential fluid for 4WD and AWD vehicles.',
 40000, 40000, NULL, NULL,
 'petrol,diesel,hybrid,lpg', NULL, NULL, NULL,
 'Differential Fluid Service',
 'Differential fluid service due on your {{vehicleLabel}}',
 'If your vehicle is 4WD or AWD, the differential fluid should be replaced every 40,000 km. Worn fluid causes excessive heat and wear in the diff, which can lead to costly gear damage. Particularly important after towing or off-road use.',
 'advisory',
 149.00, 249.00, 1, 18, 1, 150),

('CV joint and boot inspection',
 'Inspect constant velocity joints and rubber boots for wear and cracks.',
 80000, 40000, NULL, NULL,
 'all', NULL, NULL, NULL,
 'CV Joint Inspection',
 'CV joint inspection recommended for your {{vehicleLabel}}',
 'At higher mileage, CV joint boots can crack and split, allowing grease to escape and dirt to enter. A split boot left unchecked will destroy the CV joint. An inspection every 40,000 km from 80,000 km catches issues early and cheaply.',
 'advisory',
 89.00, 199.00, 1, 18, 1, 160),

-- ── Age-based ────────────────────────────────────────────────────────────────

('Battery replacement',
 'Car battery typically needs replacement every 3-4 years.',
 NULL, NULL, 48, 36,
 'petrol,diesel,hybrid,lpg', NULL, NULL, NULL,
 'Battery Replacement',
 'Time to check the battery on your {{vehicleLabel}}',
 'Car batteries typically last 3-4 years in Australian conditions — extreme heat accelerates battery degradation. At 4 years old, the risk of a no-start increases significantly. We can test your battery health and replace it if needed before it leaves you stranded.',
 'important',
 189.00, 299.00, 1, 24, 1, 170),

('Tyre age check',
 'Tyres should be replaced at 6 years regardless of tread depth.',
 NULL, NULL, 72, NULL,
 'all', NULL, NULL, NULL,
 'Tyre Age Check',
 'Tyre age check recommended for your {{vehicleLabel}}',
 'Rubber compounds degrade over time regardless of tread depth. Most tyre manufacturers recommend replacement at 6 years. Aged tyres are at higher risk of sidewall cracking and blowouts. Check the DOT date on your tyres — we can advise if replacement is needed.',
 'important',
 600.00, 1200.00, 1, 36, 1, 180),

('Wiper blade replacement',
 'Annual wiper blade replacement for clear wet weather visibility.',
 NULL, NULL, 12, 12,
 'all', NULL, NULL, NULL,
 'Wiper Blades',
 'Wiper blade replacement due on your {{vehicleLabel}}',
 'Wiper blades degrade in UV and heat, causing streaking and reduced visibility in heavy rain. Australian summers are hard on rubber — annual replacement ensures you can see clearly when you need it most.',
 'advisory',
 39.00, 89.00, 1, 6, 1, 190),

('Air conditioning service',
 'Re-gas and inspect the air conditioning system.',
 NULL, NULL, 24, 24,
 'all', NULL, NULL, NULL,
 'Air Conditioning Service',
 'Air conditioning service due on your {{vehicleLabel}}',
 'Air conditioning systems lose refrigerant slowly over time, reducing cooling performance. A service every 2 years re-gasses the system, checks for leaks, and ensures the cabin stays cool in Australian summer. An under-performing AC also puts extra load on the engine.',
 'advisory',
 149.00, 249.00, 1, 12, 1, 200);
