import { afterAll, beforeEach, describe, expect, it } from 'vitest'
import { handler as createHandler } from '../../src/customer/bookings/create'
import { customerEvent, parse } from '../_setup/apigw'
import { db } from '../_setup/db'

// End-to-end tests for POST /c/bookings.
//
// Uses customer 3 (nev@qubestudio.co.nz) + vehicle 4 (2026 Toyota Corolla).
// All test bookings land on a far-future date (2099-01-05, a Monday) so
// they don't collide with anything real. Cleanup deletes every booking
// on that date + the linked booking_services rows.
//
// Guards these regressions:
//   • bookings.end_time is STORED GENERATED — the INSERT must NOT set it
//     directly (production incident 2026-08-02).
//   • hoistId + assigned_staff_id must both be populated at create time.
//   • availability check must fire before the INSERT (past dates,
//     unlisted times, mismatched hoists).

const CUSTOMER_ID = 3
const VEHICLE_ID  = 4
const STORE_ID    = 1
const TEST_DATE   = '2099-01-05'   // Monday, no production bookings possible
const BRAKE_SVC   = 12             // 'Brake Inspection (full)' — category=brakes

async function purgeTestBookings() {
  // Cascade: delete booking_services first, then the bookings.
  await db().query(
    `DELETE bs FROM booking_services bs
     JOIN bookings b ON b.id = bs.booking_id
     WHERE b.booking_date = ? AND b.customer_id = ?`,
    [TEST_DATE, CUSTOMER_ID],
  )
  await db().query(
    'DELETE FROM bookings WHERE booking_date = ? AND customer_id = ?',
    [TEST_DATE, CUSTOMER_ID],
  )
}

beforeEach(purgeTestBookings)
afterAll(purgeTestBookings)

function baseBody(overrides: Record<string, unknown> = {}) {
  return {
    vehicleId:      VEHICLE_ID,
    storeId:        STORE_ID,
    date:           TEST_DATE,
    time:           '08:30',
    hoistId:        1,               // Howard's hoist — covers Brake Service
    type:           'drop_off',
    serviceTypeIds: [BRAKE_SVC],
    notes:          null,
    ...overrides,
  }
}

describe('POST /c/bookings — happy path', () => {
  it('creates a booking with hoist_id + assigned_staff_id + end_time populated', async () => {
    const { status, body } = parse(await createHandler(customerEvent(CUSTOMER_ID, {
      method: 'POST', body: baseBody(),
    })) as any)

    expect(status).toBe(201)
    expect(body.booking).toBeDefined()
    expect(body.booking.time).toBe('08:30')
    expect(body.booking.hoist).toEqual({ id: 1, name: 'Hoist 1' })
    expect(body.booking.tech).toEqual({ id: 3, name: 'Howard Rodda' })
    expect(body.booking.bookingRef).toMatch(/^[A-Z0-9]{8}$/)

    // DB truth — this is the regression guard for today's bug.
    const [[row]] = await db().query<any[]>(
      `SELECT hoist_id, assigned_staff_id, estimated_duration_mins,
              TIME_FORMAT(booking_time, '%H:%i') AS start,
              TIME_FORMAT(end_time,     '%H:%i') AS end_time
       FROM bookings WHERE id = ?`,
      [body.booking.id],
    )
    expect(row.hoist_id).toBe(1)
    expect(row.assigned_staff_id).toBe(3)
    expect(row.start).toBe('08:30')
    expect(row.end_time).toBe('09:30')                   // auto-generated by MySQL
    expect(row.estimated_duration_mins).toBe(60)
  })

  it('booking_services rows are linked to every requested service', async () => {
    const { body } = parse(await createHandler(customerEvent(CUSTOMER_ID, {
      method: 'POST', body: baseBody({ serviceTypeIds: [12, 9] }),   // brakes + brake pad
    })) as any)

    const [rows] = await db().query<any[]>(
      'SELECT service_type_id FROM booking_services WHERE booking_id = ? ORDER BY service_type_id',
      [body.booking.id],
    )
    expect(rows.map(r => r.service_type_id)).toEqual([9, 12])
  })

  it('picks a different tech when a different hoistId is chosen', async () => {
    const { body } = parse(await createHandler(customerEvent(CUSTOMER_ID, {
      method: 'POST', body: baseBody({ hoistId: 2 }),                // Nev's hoist
    })) as any)
    expect(body.booking.hoist.id).toBe(2)
    expect(body.booking.tech.id).toBe(8)
    expect(body.booking.tech.name).toBe('Nev Rodda')
  })
})

describe('POST /c/bookings — validation', () => {
  it('rejects missing hoistId (was silently defaulted before the lock-in change)', async () => {
    const { status, body } = parse(await createHandler(customerEvent(CUSTOMER_ID, {
      method: 'POST', body: { ...baseBody(), hoistId: undefined },
    })) as any)
    expect(status).toBe(422)
    expect(body.error.message).toMatch(/hoistId is required/)
  })

  it('rejects a time that doesn\'t match an active slot', async () => {
    const { status, body } = parse(await createHandler(customerEvent(CUSTOMER_ID, {
      method: 'POST', body: baseBody({ time: '09:45' }),
    })) as any)
    expect(status).toBe(422)
    expect(body.error.message).toMatch(/not a bookable slot/)
  })

  it('rejects a hoistId that doesn\'t cover the requested service', async () => {
    // The Tyre Bay (hoist 4) only has service_roles = ["Tyre Fitting"].
    // Requesting a brake service via that hoist must fail.
    const { status, body } = parse(await createHandler(customerEvent(CUSTOMER_ID, {
      method: 'POST', body: baseBody({ hoistId: 4, serviceTypeIds: [BRAKE_SVC] }),
    })) as any)
    expect(status).toBe(422)
    expect(body.error.message).toMatch(/not available/)
  })

  it('rejects a past date', async () => {
    const yesterday = new Date(Date.now() - 86_400_000).toISOString().slice(0, 10)
    const { status } = parse(await createHandler(customerEvent(CUSTOMER_ID, {
      method: 'POST', body: baseBody({ date: yesterday }),
    })) as any)
    expect(status).toBe(422)
  })

  it('rejects when serviceTypeIds is empty', async () => {
    const { status, body } = parse(await createHandler(customerEvent(CUSTOMER_ID, {
      method: 'POST', body: baseBody({ serviceTypeIds: [] }),
    })) as any)
    expect(status).toBe(422)
    expect(body.error.message).toMatch(/serviceTypeIds/)
  })
})

describe('POST /c/bookings — hoist capacity', () => {
  it('the second booking for the same (date, time, hoist) is refused', async () => {
    // First booking — grabs hoist 1 at 08:30
    const first = parse(await createHandler(customerEvent(CUSTOMER_ID, {
      method: 'POST', body: baseBody({ hoistId: 1 }),
    })) as any)
    expect(first.status).toBe(201)

    // Second attempt on the same hoist + slot — the availability check
    // should see it as booked and reject.
    const second = parse(await createHandler(customerEvent(CUSTOMER_ID, {
      method: 'POST', body: baseBody({ hoistId: 1 }),
    })) as any)
    expect(second.status).toBe(422)
    expect(second.body.error.message).toMatch(/not available/)
  })
})
