import { afterAll, beforeEach, describe, expect, it } from 'vitest'
import { randomUUID } from 'node:crypto'
import { handler as createHandler } from '../../src/public/booking-flow/bookings-create'
import { publicEvent, parse } from '../_setup/apigw'
import { db } from '../_setup/db'

// End-to-end tests for POST /public/bookings — the guest booking flow
// at workshop.rodz.com.au/book. Turnstile is skipped because
// TURNSTILE_SECRET isn't set in the test env (handler falls back to
// "always pass" with a console.warn — verified in the code).
//
// Uses a test-only customer email + rego so we don't collide with real
// data. Cleanup removes the created customer, vehicle, booking, and
// linked owner + services rows.
//
// Guards the same regression as the /c/bookings tests: end_time must
// stay auto-generated by MySQL (STORED GENERATED column). Also verifies
// the hoist + tech lock-in that unblocked the guest flow.

const STORE_ID    = 1
const TEST_DATE   = '2099-01-05'   // future Monday, no production data
const TEST_EMAIL  = 'booking-test@vitest.local'
const TEST_REGO   = 'VITEST'
const BRAKE_SVC   = 12

async function purge() {
  // Wipe every trace of the test customer + vehicle.
  const [custRows] = await db().query<any[]>('SELECT id FROM customers WHERE email = ?', [TEST_EMAIL])
  const [vehRows]  = await db().query<any[]>('SELECT id FROM vehicles WHERE rego = ?', [TEST_REGO])
  const custIds = custRows.map(r => r.id)
  const vehIds  = vehRows.map(r => r.id)
  if (custIds.length || vehIds.length) {
    const conds: string[] = []
    const params: any[]   = []
    if (custIds.length) { conds.push(`b.customer_id IN (${custIds.map(() => '?').join(',')})`); params.push(...custIds) }
    if (vehIds.length)  { conds.push(`b.vehicle_id  IN (${vehIds.map(() => '?').join(',')})`);  params.push(...vehIds) }
    await db().query(
      `DELETE bs FROM booking_services bs
       JOIN bookings b ON b.id = bs.booking_id
       WHERE ${conds.join(' OR ')}`,
      params,
    )
    await db().query(`DELETE b FROM bookings b WHERE ${conds.join(' OR ')}`, params)
  }
  if (vehIds.length) {
    await db().query(
      `DELETE FROM vehicle_owners WHERE vehicle_id IN (${vehIds.map(() => '?').join(',')})`,
      vehIds,
    )
    await db().query(
      `DELETE FROM vehicles WHERE id IN (${vehIds.map(() => '?').join(',')})`,
      vehIds,
    )
  }
  if (custIds.length) {
    await db().query(
      `DELETE FROM customers WHERE id IN (${custIds.map(() => '?').join(',')})`,
      custIds,
    )
  }
}

beforeEach(purge)
afterAll(purge)

function baseBody(overrides: Record<string, any> = {}) {
  return {
    customer: { firstName: 'Test', lastName: 'Guest', email: TEST_EMAIL, mobile: '0400000000' },
    vehicle:  {
      year: 2020, make: 'Toyota', model: 'Corolla', rego: TEST_REGO, regoState: 'VIC',
      fuelType: 'petrol', transmission: 'automatic',
    },
    booking: {
      storeId:        STORE_ID,
      date:           TEST_DATE,
      time:           '08:30',
      hoistId:        1,
      serviceTypeIds: [BRAKE_SVC],
      customerNotes:  null,
    },
    meta: { sessionId: randomUUID() },
    turnstileToken: 'skip',   // ignored because TURNSTILE_SECRET is unset
    ...overrides,
  }
}

describe('POST /public/bookings — happy path', () => {
  it('creates a fully-locked booking with hoist + tech + auto end_time', async () => {
    const { status, body } = parse(await createHandler(publicEvent({
      method: 'POST', body: baseBody(),
    })) as any)

    expect(status).toBe(201)
    expect(body.booking).toBeDefined()
    expect(body.booking.bookingReference).toMatch(/^[A-Z0-9]{8}$/)
    expect(body.booking.time).toBe('08:30')
    expect(body.booking.hoist).toEqual({ id: 1, name: 'Hoist 1' })
    expect(body.booking.tech).toEqual({ id: 3, name: 'Howard Rodda' })

    // DB truth — this is the regression guard for the end_time incident.
    const [[row]] = await db().query<any[]>(
      `SELECT hoist_id, assigned_staff_id, estimated_duration_mins,
              TIME_FORMAT(booking_time, '%H:%i') AS start,
              TIME_FORMAT(end_time,     '%H:%i') AS end_time,
              booking_source, status
       FROM bookings WHERE id = ?`,
      [body.booking.bookingId],
    )
    expect(row.hoist_id).toBe(1)
    expect(row.assigned_staff_id).toBe(3)
    expect(row.start).toBe('08:30')
    expect(row.end_time).toBe('09:30')          // auto-generated by MySQL
    expect(row.estimated_duration_mins).toBe(60)
    expect(row.booking_source).toBe('website')
    expect(row.status).toBe('pending')
  })

  it('creates the customer + vehicle + owner link', async () => {
    const { body } = parse(await createHandler(publicEvent({
      method: 'POST', body: baseBody(),
    })) as any)

    const [[c]] = await db().query<any[]>('SELECT id, first_name, last_name FROM customers WHERE email = ?', [TEST_EMAIL])
    expect(c).toBeDefined()
    expect(c.first_name).toBe('Test')

    const [[v]] = await db().query<any[]>('SELECT id, make, model FROM vehicles WHERE rego = ?', [TEST_REGO])
    expect(v).toBeDefined()
    expect(v.make).toBe('Toyota')

    const [[link]] = await db().query<any[]>(
      'SELECT id FROM vehicle_owners WHERE customer_id = ? AND vehicle_id = ? AND is_current = 1',
      [c.id, v.id],
    )
    expect(link).toBeDefined()
  })

  it('is idempotent — replaying the same sessionId returns the same booking', async () => {
    const body = baseBody()
    const first  = parse(await createHandler(publicEvent({ method: 'POST', body })) as any)
    const second = parse(await createHandler(publicEvent({ method: 'POST', body })) as any)

    expect(first.status).toBe(201)
    expect(second.status).toBe(200)               // idempotent replay
    expect(second.body.booking.bookingReference).toBe(first.body.booking.bookingReference)
    expect(second.body.booking.idempotent).toBe(true)
  })
})

describe('POST /public/bookings — validation', () => {
  it('rejects missing hoistId', async () => {
    const body = baseBody()
    body.booking.hoistId = undefined as any
    const { status, body: res } = parse(await createHandler(publicEvent({
      method: 'POST', body,
    })) as any)
    expect(status).toBe(422)
    expect(res.error.message).toMatch(/hoistId is required/)
  })

  it('rejects an unlisted time', async () => {
    const body = baseBody()
    body.booking.time = '09:45'
    const { status, body: res } = parse(await createHandler(publicEvent({
      method: 'POST', body,
    })) as any)
    expect(status).toBe(422)
    expect(res.error.message).toMatch(/not a bookable slot/)
  })

  it('rejects a hoist that doesn\'t cover the requested service', async () => {
    const body = baseBody()
    body.booking.hoistId = 4               // Tyre Bay — only 'Tyre Fitting'
    body.booking.serviceTypeIds = [BRAKE_SVC]
    const { status, body: res } = parse(await createHandler(publicEvent({
      method: 'POST', body,
    })) as any)
    expect(status).toBe(422)
    expect(res.error.code).toBe('SLOT_UNAVAILABLE')
    expect(res.error.message).toMatch(/not available/)
  })
})
